### ISSUE TITLE
how to config chromedriver in this situation？

### ISSUE THREAD

**Issue by IsraelSuen** [BahramJannesar/ArchdailyProjectDownloader#1]
C:\Users\20190627-1>python G:\ArchdailyProjectDownloader-master\main.py
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\selenium\webdriver\common\service.py", line 76, in start
    stdin=PIPE)
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "G:\ArchdailyProjectDownloader-master\main.py", line 17, in <module>
    driver = webdriver.Chrome(chromedriver)
  File "C:\ProgramData\Anaconda3\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 68, in __init__
    self.service.start()
  File "C:\ProgramData\Anaconda3\lib\site-packages\selenium\webdriver\common\service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver.exe' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

**Comment by rickkk856** [comment]
you need to download the cromedriver at https://chromedriver.chromium.org/downloads and put it at `G:\ArchdailyProjectDownloader-master\driver`

Just make sure you donwload the correct version, in my case its 99.0.4844.51
![image](https://user-images.githubusercontent.com/62864640/157264855-ba96cfa2-1cea-496f-a65e-01b221991ef3.png)
